"""
Branded PDF reports for the business (Tara) section.

Pure rendering: it receives an already-computed payload from routes.py (so the
money maths stays in one place) and lays it out with reportlab in the tara
brand — green #0f6e56 / deep green #083d30 / gold #ef9f27.
"""
from io import BytesIO
from xml.sax.saxutils import escape

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

GREEN = colors.HexColor("#0f6e56")
GREEN_DARK = colors.HexColor("#083d30")
GREEN_LIGHT = colors.HexColor("#e7f2ed")
GOLD = colors.HexColor("#ef9f27")
GOLD_LIGHT = colors.HexColor("#fff7ea")
INK = colors.HexColor("#22302b")
MUTED = colors.HexColor("#6b7a74")
LINE = colors.HexColor("#dfe7e3")

CONTENT_W = 178 * mm  # A4 width (210mm) minus 16mm margins each side


def _styles():
    ss = getSampleStyleSheet()
    return {
        "h2": ParagraphStyle("h2", parent=ss["Normal"], fontName="Helvetica-Bold",
                             fontSize=12.5, textColor=GREEN_DARK, spaceBefore=14, spaceAfter=6),
        "body": ParagraphStyle("body", parent=ss["Normal"], fontSize=9.5, leading=13, textColor=INK),
        "muted": ParagraphStyle("muted", parent=ss["Normal"], fontSize=8.5, leading=12, textColor=MUTED),
        "cell": ParagraphStyle("cell", parent=ss["Normal"], fontSize=9, leading=12, textColor=INK),
        "cellb": ParagraphStyle("cellb", parent=ss["Normal"], fontName="Helvetica-Bold",
                                fontSize=9, leading=12, textColor=colors.white),
    }


def _kpi_cell(label: str, value: str, accent: bool = False) -> Paragraph:
    colour = "#083d30" if not accent else "#b47614"
    return Paragraph(
        f'<font size="15" color="{colour}"><b>{escape(value)}</b></font><br/>'
        f'<font size="8" color="#6b7a74">{escape(label)}</font>',
        ParagraphStyle("kpi", fontName="Helvetica", fontSize=9, leading=19),
    )


def _table(headers, rows, widths, st):
    """A branded table: green header, zebra body."""
    data = [[Paragraph(h, st["cellb"]) for h in headers]]
    for r in rows:
        data.append([Paragraph(str(c), st["cell"]) for c in r])
    t = Table(data, colWidths=widths, repeatRows=1, hAlign="LEFT")
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), GREEN),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("LINEBELOW", (0, 0), (-1, -1), 0.4, LINE),
    ]
    for i in range(1, len(data)):
        if i % 2 == 0:
            style.append(("BACKGROUND", (0, i), (-1, i), GREEN_LIGHT))
    t.setStyle(TableStyle(style))
    return t


def render_report_pdf(d: dict) -> bytes:
    st = _styles()
    cur = d.get("currency", "KSh")
    k = d.get("kpis", {})

    def header_footer(canvas, doc_):
        canvas.saveState()
        w, h = A4
        canvas.setFillColor(GREEN)
        canvas.rect(0, h - 26 * mm, w, 26 * mm, stroke=0, fill=1)
        canvas.setFillColor(GOLD)
        canvas.circle(22 * mm, h - 13 * mm, 5.4 * mm, stroke=0, fill=1)
        canvas.setFillColor(GREEN_DARK)
        canvas.setFont("Helvetica-Bold", 11)
        canvas.drawCentredString(22 * mm, h - 14.8 * mm, "t")
        canvas.setFillColor(colors.white)
        canvas.setFont("Helvetica-Bold", 17)
        canvas.drawString(31 * mm, h - 12.4 * mm, "tara")
        canvas.setFont("Helvetica", 9)
        canvas.drawString(31 * mm, h - 18.2 * mm, d.get("shop") or "Shop report")
        canvas.setFont("Helvetica-Bold", 11.5)
        canvas.drawRightString(w - 16 * mm, h - 12.4 * mm, d.get("period_label", ""))
        canvas.setFont("Helvetica", 9)
        canvas.drawRightString(w - 16 * mm, h - 18.2 * mm, d.get("range_label", ""))
        # footer
        canvas.setStrokeColor(LINE)
        canvas.line(16 * mm, 14 * mm, w - 16 * mm, 14 * mm)
        canvas.setFillColor(MUTED)
        canvas.setFont("Helvetica", 8)
        canvas.drawString(16 * mm, 9.5 * mm, f"Generated by tara · {d.get('generated_at', '')}")
        canvas.drawRightString(w - 16 * mm, 9.5 * mm, f"Page {doc_.page}")
        canvas.restoreState()

    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=16 * mm, rightMargin=16 * mm, topMargin=34 * mm, bottomMargin=20 * mm,
        title=f"tara — {d.get('period_label', 'Report')}", author="tara",
    )

    story = []

    # ---- KPI grid -------------------------------------------------------
    third = CONTENT_W / 3.0
    kpi = Table([
        [_kpi_cell("Total sales", f"{k.get('sales_f','0')} {cur}"),
         _kpi_cell("Credit given", f"{k.get('credit_given_f','0')} {cur}"),
         _kpi_cell("Payments received", f"{k.get('payments_f','0')} {cur}")],
        [_kpi_cell("Money out (restock/expenses)", f"{k.get('cash_out_f','0')} {cur}"),
         _kpi_cell("Net cash", f"{k.get('net_cash_f','0')} {cur}", accent=True),
         _kpi_cell("Profit", f"{k.get('profit_f','0')} {cur}")],
    ], colWidths=[third, third, third], hAlign="LEFT")
    kpi.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), GREEN_LIGHT),
        ("BACKGROUND", (1, 1), (1, 1), GOLD_LIGHT),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("GRID", (0, 0), (-1, -1), 3, colors.white),
    ]))
    story.append(kpi)
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        f"{k.get('count', 0)} sales recorded in this period. "
        f"Net cash = sales − credit given + payments − money out.", st["muted"]))

    # ---- narrative ------------------------------------------------------
    if d.get("summary"):
        story.append(Paragraph("Summary", st["h2"]))
        story.append(Paragraph(escape(d["summary"]).replace("\n", "<br/>"), st["body"]))

    # ---- breakdown ------------------------------------------------------
    if d.get("breakdown"):
        story.append(Paragraph("Sales over time", st["h2"]))
        story.append(_table(["Period", f"Sales ({cur})"],
                            [[b["label"], b["sales_f"]] for b in d["breakdown"]],
                            [CONTENT_W * 0.62, CONTENT_W * 0.38], st))

    # ---- top items ------------------------------------------------------
    if d.get("top_items"):
        story.append(Paragraph("Best sellers", st["h2"]))
        story.append(_table(["Item", f"Sold ({cur})"],
                            [[escape(str(i["item"])), i["sold_f"]] for i in d["top_items"]],
                            [CONTENT_W * 0.62, CONTENT_W * 0.38], st))

    # ---- debts ----------------------------------------------------------
    if d.get("debts"):
        story.append(Paragraph("Money owed to you", st["h2"]))
        story.append(_table(["Customer", f"Owes ({cur})"],
                            [[escape(str(x["name"] or "—")), x["balance_f"]] for x in d["debts"]],
                            [CONTENT_W * 0.62, CONTENT_W * 0.38], st))

    # ---- transactions ---------------------------------------------------
    if d.get("transactions"):
        story.append(Paragraph("Transactions", st["h2"]))
        story.append(_table(
            ["Date", "Type", "Item", "Qty", f"Amount ({cur})", "Customer"],
            [[t["date"], t["type"], escape(str(t["item"] or "—")), t["qty"],
              t["amount_f"], escape(str(t["customer"] or "—"))] for t in d["transactions"]],
            [22 * mm, 20 * mm, 48 * mm, 16 * mm, 30 * mm, 42 * mm], st))
        if d.get("transactions_truncated"):
            story.append(Spacer(1, 4))
            story.append(Paragraph(
                f"Showing the {len(d['transactions'])} most recent of {d['transactions_total']} "
                f"transactions in this period.", st["muted"]))

    if not d.get("transactions"):
        story.append(Paragraph("No activity recorded in this period.", st["muted"]))

    doc.build(story, onFirstPage=header_footer, onLaterPages=header_footer)
    return buf.getvalue()
